### ISSUE TITLE
"Enter Binds" dialog shown when SQL contains colon. Why?

### ISSUE THREAD

**Issue by PhilippSalvisberg** [Trivadis/sqldev-jdbc-proxy#2]
Create table `t` with a simple JSON document:

```sql
create table t (c variant);
insert into t select (parse_json ('{"a1":{"b1":"value b1"}, "a2":"value2"}'));
```

This query works in snowsql:

```sql
select c:a1.b1::varchar(10) as v1, 
       c:a2::varchar(10) as v2 
  from t;
```

it produces this result:

```
+----------+--------+                                                           
| V1       | V2     |
|----------+--------|
| value b1 | value2 |
+----------+--------+
1 Row(s) produced. Time Elapsed: 0.538s
```

When executed in SQL Developer the following dialog is shown:

![image](https://user-images.githubusercontent.com/3883171/105027179-bd503a80-5a4f-11eb-9f46-8d3ba0f8e7a9.png)

**Comment by PhilippSalvisberg** [comment]
SQL Developer's parser is based on the grammar of SQL*Plus (SQLcl to be precise), SQL and PL/SQL. A colon followed by an identifier is recognized as a bind variable. In this case `a1`  and `a2`.

A workaround is to use the full version of the `get_path` function (see also [Snowflake's documentation](https://docs.snowflake.com/en/sql-reference/functions/get_path.html)). This works:

```
select get_path(c,'a1.b1')::varchar(10) as v1, 
       get_path(c,'a2')::varchar(10) as v2 
  from t;
```

Here's the screenshot:

![image](https://user-images.githubusercontent.com/3883171/105028024-c55caa00-5a50-11eb-8ea5-f715fa7cd01a.png)

Interesting is, that SQL Developer has no problems with the alternative variant of the `cast` function (`::`, [see documentation](https://docs.snowflake.com/en/sql-reference/functions/cast.html)).

**Comment by bogomolga** [comment]
how to disable dialog window Enter Binds in Oracle SQL Developer
